export enum RouteType {
  Home = '/',
  Projects = '/projects',
  About = '/about',
  Contact = '/contact',
  Render = '/render',
  Tictactoe = '/tictactoe',
  Fuelprices = '/fuelprices',
  Property = '/property',
  Mrna = '/mrna',
  Secondary = '/secondary',
  Seqalign = '/seqalign',
  Heatmap = '/heatmap',
  RandomBio = '/randombio',
  Minesweeper = '/minesweeper',
  JsSim = '/jssimulator',

  BlogHome = '/blog',
  // BlogSearch = '/blog/search',
  BlogPostCreate = '/blog/post',
  BlogLogin = '/blog/login',
  BlogPost = '/blog/post/:postId',
  BlogRegister = '/blog/register',
}

